%% Format

% varible name [variable type and size]
% description

% [1] indicates a scalar
% [a,b,c] is an array with dimensions a,b,c

%% LinkPropertiesStruct

% properties of the individual links used in the MNN
% data comes from CAD and FEA

% L1 [1]
% length of individual link used in MNN
% units: m

% L2 [1]
% X-component of beam under 60 degrees
% units: m

% L3 [1]
% Y-component of beam under 60 degrees
% units: m

% MaxLinkElongation [1]
% maximum allowed link elongation allowed for factor of safety
% units: m

% MaxLinkCompression [1]
% maximum allowed link compression for factor of safety
% units: m

% k55 [1]
% off-axis stiffness, force acting perpendicular with no allowed rotation
% units: N/m

% k56 [1]
% off-axis-stiffness, force acting perpendicular with allowed rotation
% units: N/rad

% k66 [1]
% off-axis-stiffness, moment acting with allowed perpendicular translation
% units: N m/rad

% kLinPassive [1]
% passive linear stiffness of element
% units: N/m

% kLinMax [1]
% maximum controllable stiffness
% units: N/m

% kLinMin [1]
% minimum controllable stiffness (can be negative)
% units: N/m

%% LatticeGeometryStruct

% geometry and mesh matrices for a given lattice
% some fields are user inputs, the rest is generated by
% triangleLatticeFunction and squareLatticeFunction (not yet implemented)

% latticeType [1]
% Type of lattice, 1) triangular 2) square

% NinputANDoutputArray [NinputANDoutputIter]
% Width of lattice, determioned by the number of input and output nodes
% input can be a vector for parametric studies

% NlayersArray [NlayersIter]
% depth of lattice, determined by the number of ground connection layers
% between input and output
% input can be a vector for parametric studies

% DOI = 3 [1]
% dimensions in space

% Ncoord [1]
% number of nodes in the lattice

% Nbeams [1]
% number of beams in the lattice

% coord_initial [Ncoord,DOI]
% x,y,z coordinates of each node in undeformed state

% connectivity [Nbeams,2]
% node indices connected to each beam
% connectivity(k,:) = [a,b] means that beam k connects nodes a and b

% bound [Nlayers * 2]
% node indices that are grounded

% inputNodes [NinputANDoutputArray]
% node indices that are used as inputs

% outputNodes [NinputANDoutputArray]
% node indices that are used as outputs


%% 



